fix: update timestamp format
rustic-ai/ui-components pull request #119
Opened 2024-05-03 18:16 UTC by kaseyvee

## Changes
- update timestamp format of `formatDateAndTime` output based on issue #111
- add more stories to `TimeStamp`

## Screenshots
### MessageCanvas
#### Before
<img width="352" alt="Screenshot 2024-05-03 at 11 09 29 AM" src="https://github.com/rustic-ai/ui-components/assets/111031789/41fad67d-669f-4a7c-8fe2-b4bbc84e4a6a">

#### After
<img width="376" alt="Screenshot 2024-05-03 at 11 11 32 AM" src="https://github.com/rustic-ai/ui-components/assets/111031789/fe05f0f5-6b5f-4111-aca6-50f5d7ef1e19">

### Timestamp
#### Before
<img width="437" alt="Screenshot 2024-05-03 at 11 08 54 AM" src="https://github.com/rustic-ai/ui-components/assets/111031789/29250c2b-a653-44b0-ab7b-00ad2762678b">

#### After
<img width="458" alt="Screenshot 2024-05-03 at 10 59 41 AM" src="https://github.com/rustic-ai/ui-components/assets/111031789/fe8d0c37-6351-427d-9205-e175fabaf7ab">

2024-05-03 18:17 UTC, kaseyvee commented
@RenataDzotova

2024-05-03 19:25 UTC, Shiti submitted a review, later dismissed

2024-05-03 19:41 UTC, lyjeileen requested changes

2024-05-03 19:41 UTC, lyjeileen commented on src/components/helper.ts
> +  const dataAndTimeConnector = isDifferentYear ? ' at ' : ', '
```suggestion
  const dateAndTimeConnector = isDifferentYear ? ' at ' : ', '
```

2024-05-03 19:41 UTC, lyjeileen commented on src/components/helper.ts
> +    dataAndTimeConnector +
```suggestion
    dateAndTimeConnector +
```

2024-05-03 20:09 UTC, lyjeileen approved these changes

2024-05-05 03:34 UTC, Shiti approved these changes

2024-05-05 03:34 UTC, merged