fix: override button text transform
rustic-ai/ui-components pull request #143
Opened 2024-05-17 23:11 UTC by kaseyvee

## Changes
- override `MuiButton` text transform
    - none of the Figma designs use buttons with all uppercase, which is the MUI default for buttons
- remove text transform styling from `PopoverMenu` css

## Screenshots
### Before
<img width="398" alt="Screenshot 2024-05-17 at 3 53 26 PM" src="https://github.com/rustic-ai/ui-components/assets/111031789/e3bc3d7a-7d7d-454f-a98a-96d29815f3d2">
<img width="398" alt="Screenshot 2024-05-17 at 3 53 48 PM" src="https://github.com/rustic-ai/ui-components/assets/111031789/72abaa48-5e7c-4180-a201-36e48f814890">

### After
<img width="398" alt="Screenshot 2024-05-17 at 3 52 42 PM" src="https://github.com/rustic-ai/ui-components/assets/111031789/fe2b932c-136f-483e-b634-1fd68b1c19fd">
<img width="398" alt="Screenshot 2024-05-17 at 3 52 59 PM" src="https://github.com/rustic-ai/ui-components/assets/111031789/33ddf10c-e834-4e1b-93bb-b0148a1c14bb">

### PopoverMenu with text (no change)
<img width="398" alt="Screenshot 2024-05-17 at 4 04 28 PM" src="https://github.com/rustic-ai/ui-components/assets/111031789/397dfd0b-2f59-49f8-a4aa-2db007db4a3a">

2024-05-17 23:15 UTC, Shiti requested changes

2024-05-17 23:15 UTC, Shiti commented on src/rusticTheme.ts
> +        textTransform: 'none',
```suggestion
        textTransform: 'capitalize',
```

2024-05-17 23:15 UTC, Shiti commented on src/rusticTheme.ts
> +        textTransform: 'none',
This can be included in baseTheme. A new variable is not required

2024-05-17 23:22 UTC, lyjeileen commented
I think Lauren mentioned the first letter of every word should be capitalized

2024-05-17 23:59 UTC, Shiti approved these changes

2024-05-18 00:22 UTC, lyjeileen approved these changes

2024-05-18 00:22 UTC, merged