feat(popoverMenu): support href
rustic-ai/ui-components pull request #167
Opened 2024-05-28 03:21 UTC by lyjeileen

## Change:
- Add `href` and `downloadFileName` to `PopoverMenuItem`
- Update stories and tests

Question: Should I also add target?

## Video
### Link
![May-27-2024 20-19-17](https://github.com/rustic-ai/ui-components/assets/103023797/98b7087a-bcaa-44d4-8c44-7822e7b38d83)
### Download
![May-27-2024 20-20-49](https://github.com/rustic-ai/ui-components/assets/103023797/29302264-3954-4cff-aed4-06d90e62b0fa)

2024-05-28 20:45 UTC, lyjeileen commented on src/components/menu/popoverMenu.stories.tsx
> +          '  downloadFileName: An optional string specifying the filename for downloading content. This works in conjunction with the href property to allow users to download a file when the menu ite
I'm wondering if I should change it to `download` to match with the download attribute for anchor

2024-05-28 21:07 UTC, kaseyvee commented on src/components/menu/popoverMenu.stories.tsx
> +          '  downloadFileName: An optional string specifying the filename for downloading content. This works in conjunction with the href property to allow users to download a file when the menu ite
I think `download` is okay

2024-05-29 21:58 UTC, Shiti requested changes

2024-05-29 23:23 UTC, Shiti approved these changes

2024-05-29 23:25 UTC, kaseyvee approved these changes

2024-05-29 23:28 UTC, merged